### ISSUE TITLE
X-Pj-Cache-Status: miss

### ISSUE THREAD

**Issue by ntimo** [pressjitsu/pj-page-cache-red#10]
Hi their,
I just installed your plugin and it seems like it does not work for me :(

Here is what the curl gives me:

Server: nginx
< Date: Wed, 14 Dec 2016 11:43:05 GMT
< Content-Type: text/html; charset=UTF-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< X-Powered-By: PHP/5.6.29
< X-Pj-Cache-Status: miss
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
< Pragma: no-cache
< Link: <https://url..../wp-json/>; rel="https://api.w.org/", <https://url.....de/?p=1006>; rel=shortlink
< Set-Cookie: PHPSESSID=dihuh83z2rz2rh2i6; path=/
< Vary: Accept-Encoding
< X-Powered-By: PleskLin

**Comment by ntimo** [comment]
I do also get this on a freshly installed wordpress page:

< HTTP/1.1 200 OK
< Server: nginx
< Date: Wed, 14 Dec 2016 13:03:50 GMT
< Content-Type: text/html; charset=UTF-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< X-Powered-By: PHP/7.1.0
< X-Pj-Cache-Status: miss
< X-Pingback: https://wordpress.dawdadadt.com/xmlrpc.php
< Link: <https://wordpress.dadadadat.com/wp-json/>; rel="https://api.w.org/", <https://wordpress.idawdadawda.com/?p=4>; rel=shortlink
< Vary: Accept-Encoding
< X-Powered-By: PleskLin

**Comment by soulseekah** [comment]
Thanks for your report.

The first case doesn't work because you have a session in there somewhere. Read more about issues with PHP Sessions and caching here: https://pressjitsu.com/blog/wordpress-sessions-performance/

The second time might not work for a number of reasons (some of which are obvious, so my apologies):

1. You requested the page for the very first time. Does the second time yield a miss as well?
2. There are issues connecting to the Redis server. Are you running Redis? Are the connection details correct? Is there any information in Redis? Or is the keystore completely empty?

Looking at the PHP error logs with DEBUG mode turned on should help here, too.

Thanks and let us know how it goes.

**Comment by ntimo** [comment]
Hi their,

thank you it indeed was a plugin that created the PHPSESSID. It was the give plugin... I will have to contact the developer. Now my page loads in 700-800ms that just amazing! Thank you for making this plugin!
