### ISSUE TITLE
[inquiry] - is this WooCommerce friendly?

### ISSUE THREAD

**Issue by wkhayrattee** [pressjitsu/pj-page-cache-red#29]
Hi, have anyone used this plugin with the likes of WooCommerce?
Does it play well?

thank you

**Comment by soulseekah** [comment]
Yes. This plugin has been used in production for hundreds of WooCommerce sites at https://pressjitsu.com for many many years.

**Comment by wkhayrattee** [comment]
That's awesome!
Dear @soulseekah would you mind share some configurations you found working best for WooCommerce?

**Comment by soulseekah** [comment]
This caching plugin was conceived to be a zero-configuration optimal default. Meaning you don't need to configure it much for default installs of WordPress and WooCommerce.

For anything else please refer to the readme. Cheers :)

**Comment by wkhayrattee** [comment]
thanks @soulseekah 
One last thing, if I use this plugin, I don't need something like Varnish?
What's your advice?

**Comment by soulseekah** [comment]
Varnish can be used one of the final layers that don't let HTTP requests hit PHP.

We tend to use FCGI cache in nginx instead of Varnish. But you can use Varnish.

Caching layer setups can be complicated, for example: browser cache -> cloudflare -> Varnish -> nginx -> PHP -> Redis/WordPress

Each step needs to be able handle invalidation, so try to keep things simple. This plugin is the the closest to WordPress, the very first step. It can be the final step.

Good luck.

**Comment by ainsleyclark** [comment]
Hi there, does it automatically remove caching from checkout, basket etc? Or will that have to be done manually?

**Comment by soulseekah** [comment]
It does not cache checkout, carts, etc.
