### ISSUE TITLE
Handle `wordpress_test_cookie` better

### ISSUE THREAD

**Issue by pj-dave** [pressjitsu/pj-page-cache-red#8]
Sometimes due to a cache hit, the `wordpress_test_cookie` cookie on `wp-login.php` is not set, causing a failure when attempting to login for the first time.

**Comment by kochtopf** [comment]
My quick fix was: Just remove the 'wordpress_test_cookie' from private static $ignore_cookies. THe annoying cookie warning at login would be seen for one time only. After that you could login/out without warning because 'wp-settings*' has been set for a year. It only comes back once you clean your cookie jar or use private browsing.

**Comment by kochtopf** [comment]
this would fix it for me
348a349

> if ( $key == 'wordpress_test_cookie' && substr( self::parse_request_uri( $_SERVER['REQUEST_URI'] ), 0, 13 ) === '/wp-login.php' ) return true;
